// Sample Farmers Data (replace with API/DB later)
const farmers = [
  {
    id: 1,
    name: "Florence Karanja",
    location: "Lari/Kirenga Ward",
    orders: 3,
    status: "Pending Payment",
    sustainabilityScore: 65,
  },
  {
    id: 2,
    name: "Grace Jepkorir",
    location: "Dagoretti South",
    orders: 10,
    status: "Inactive",
    sustainabilityScore: 56,
  },
  {
    id: 3,
    name: "Michael Jepkorir",
    location: "Kabete",
    orders: 4,
    status: "Active",
    sustainabilityScore: 83,
  },
  {
    id: 4,
    name: "John Anyango",
    location: "Kiharu",
    orders: 10,
    status: "Active",
    sustainabilityScore: 64,
  },
  {
    id: 5,
    name: "Anne Nyambura",
    location: "Kijabe Ward",
    orders: 3,
    status: "Active",
    sustainabilityScore: 53,
  },
  {
    id: 6,
    name: "Lucy Omondi",
    location: "Kiambu Town",
    orders: 6,
    status: "Active",
    sustainabilityScore: 81,
  },
  {
    id: 7,
    name: "Samuel Karanja",
    location: "Lari/Kirenga Ward",
    orders: 5,
    status: "Active",
    sustainabilityScore: 96,
  },
  {
    id: 8,
    name: "Grace Njeri",
    location: "Kiambu Town",
    orders: 1,
    status: "Inactive",
    sustainabilityScore: 54,
  },
  {
    id: 9,
    name: "David Nyambura",
    location: "Thika Town",
    orders: 1,
    status: "Active",
    sustainabilityScore: 77,
  },
  {
    id: 10,
    name: "Jane Wangari",
    location: "Gatundu South",
    orders: 4,
    status: "Active",
    sustainabilityScore: 69,
  },
  {
    id: 11,
    name: "Grace Wambui",
    location: "Ol Kalou",
    orders: 7,
    status: "Active",
    sustainabilityScore: 87,
  },
  {
    id: 12,
    name: "Paul Anyango",
    location: "Kinale Ward",
    orders: 9,
    status: "Active",
    sustainabilityScore: 54,
  },
  {
    id: 13,
    name: "Esther Wambui",
    location: "Limuru",
    orders: 10,
    status: "Active",
    sustainabilityScore: 53,
  },
  {
    id: 14,
    name: "Elizabeth Mwangi",
    location: "Makadara",
    orders: 8,
    status: "Active",
    sustainabilityScore: 91,
  },
  {
    id: 15,
    name: "Stephen Anyango",
    location: "Embakasi North",
    orders: 1,
    status: "Active",
    sustainabilityScore: 76,
  },
  {
    id: 16,
    name: "Lucy Kipchumba",
    location: "Kangema",
    orders: 9,
    status: "Active",
    sustainabilityScore: 64,
  },
  {
    id: 17,
    name: "Stephen Otieno",
    location: "Kiambu Town",
    orders: 9,
    status: "Active",
    sustainabilityScore: 100,
  },
  {
    id: 18,
    name: "Catherine Kariuki",
    location: "Machakos Town",
    orders: 5,
    status: "Active",
    sustainabilityScore: 91,
  },
  {
    id: 19,
    name: "Sarah Kipchumba",
    location: "Lari",
    orders: 7,
    status: "Inactive",
    sustainabilityScore: 100,
  },
  {
    id: 20,
    name: "Mary Kariuki",
    location: "Mavoko",
    orders: 7,
    status: "Active",
    sustainabilityScore: 57,
  },
  {
    id: 21,
    name: "Michael Njeri",
    location: "Mumbuni North Ward",
    orders: 5,
    status: "Active",
    sustainabilityScore: 50,
  },
  {
    id: 22,
    name: "Peter Kimani",
    location: "Gatundu South",
    orders: 6,
    status: "Active",
    sustainabilityScore: 92,
  },
  {
    id: 23,
    name: "Mary Ochieng",
    location: "Mwihoko Ward",
    orders: 10,
    status: "Active",
    sustainabilityScore: 60,
  },
  {
    id: 24,
    name: "Ruth Achieng",
    location: "Engineer Ward",
    orders: 8,
    status: "Active",
    sustainabilityScore: 67,
  },
  {
    id: 25,
    name: "Ruth Kamau",
    location: "Mathioya",
    orders: 3,
    status: "Inactive",
    sustainabilityScore: 67,
  },
  {
    id: 26,
    name: "Lucy Mwangi",
    location: "Ruaraka",
    orders: 6,
    status: "Active",
    sustainabilityScore: 65,
  },
  {
    id: 27,
    name: "David Karanja",
    location: "Maragwa",
    orders: 9,
    status: "Active",
    sustainabilityScore: 53,
  },
  {
    id: 28,
    name: "James Wambui",
    location: "Masinga",
    orders: 10,
    status: "Pending Payment",
    sustainabilityScore: 87,
  },
  {
    id: 29,
    name: "Paul Kibet",
    location: "Gatanga",
    orders: 10,
    status: "Inactive",
    sustainabilityScore: 83,
  },
  {
    id: 30,
    name: "Sarah Jepkorir",
    location: "Mathare",
    orders: 7,
    status: "Inactive",
    sustainabilityScore: 96,
  },
  {
    id: 31,
    name: "Patrick Muthoni",
    location: "Kiambu Town",
    orders: 1,
    status: "Active",
    sustainabilityScore: 89,
  },
  {
    id: 32,
    name: "Paul Njoroge",
    location: "Ol Kalou Central Ward",
    orders: 9,
    status: "Active",
    sustainabilityScore: 66,
  },
  {
    id: 33,
    name: "Jane Kamau",
    location: "Embakasi East",
    orders: 5,
    status: "Active",
    sustainabilityScore: 73,
  },
  {
    id: 34,
    name: "Grace Kamau",
    location: "Ol Kalou",
    orders: 9,
    status: "Active",
    sustainabilityScore: 62,
  },
  {
    id: 35,
    name: "Patrick Wangari",
    location: "Kasarani",
    orders: 2,
    status: "Active",
    sustainabilityScore: 95,
  },
  {
    id: 36,
    name: "Thomas Nyambura",
    location: "Kangema",
    orders: 4,
    status: "Active",
    sustainabilityScore: 74,
  },
  {
    id: 37,
    name: "Michael Njoroge",
    location: "Ndaragwa",
    orders: 9,
    status: "Active",
    sustainabilityScore: 87,
  },
  {
    id: 38,
    name: "Michael Njeri",
    location: "Engineer Ward",
    orders: 4,
    status: "Active",
    sustainabilityScore: 96,
  },
  {
    id: 39,
    name: "John Maina",
    location: "Embakasi North",
    orders: 10,
    status: "Active",
    sustainabilityScore: 54,
  },
  {
    id: 40,
    name: "Lucy Maina",
    location: "Masinga",
    orders: 7,
    status: "Active",
    sustainabilityScore: 86,
  },
  {
    id: 41,
    name: "Sarah Kibet",
    location: "Ol Kalou Central Ward",
    orders: 6,
    status: "Pending Payment",
    sustainabilityScore: 80,
  },
  {
    id: 42,
    name: "Sarah Njeri",
    location: "Dagoretti North",
    orders: 5,
    status: "Pending Payment",
    sustainabilityScore: 59,
  },
  {
    id: 43,
    name: "Ruth Kibet",
    location: "Kiambaa",
    orders: 6,
    status: "Active",
    sustainabilityScore: 97,
  },
  {
    id: 44,
    name: "Michael Kimani",
    location: "Westlands",
    orders: 3,
    status: "Active",
    sustainabilityScore: 64,
  },
  {
    id: 45,
    name: "Catherine Kibet",
    location: "Kinale Ward",
    orders: 3,
    status: "Active",
    sustainabilityScore: 99,
  },
  {
    id: 46,
    name: "John Karanja",
    location: "Dagoretti South",
    orders: 10,
    status: "Active",
    sustainabilityScore: 72,
  },
  {
    id: 47,
    name: "Samuel Kiptoo",
    location: "Juja",
    orders: 8,
    status: "Active",
    sustainabilityScore: 85,
  },
  {
    id: 48,
    name: "Thomas Anyango",
    location: "Gatundu South",
    orders: 7,
    status: "Active",
    sustainabilityScore: 79,
  },
  {
    id: 49,
    name: "Stephen Achieng",
    location: "Kibra",
    orders: 9,
    status: "Active",
    sustainabilityScore: 52,
  },
  {
    id: 50,
    name: "Florence Kiptoo",
    location: "Gitothua Ward",
    orders: 5,
    status: "Active",
    sustainabilityScore: 100,
  },
  {
    id: 51,
    name: "Stephen Ochieng",
    location: "Masinga",
    orders: 7,
    status: "Active",
    sustainabilityScore: 61,
  },
  {
    id: 52,
    name: "George Ochieng",
    location: "Embakasi West",
    orders: 5,
    status: "Active",
    sustainabilityScore: 57,
  },
  {
    id: 53,
    name: "Peter Kimani",
    location: "Kinangop",
    orders: 6,
    status: "Active",
    sustainabilityScore: 86,
  },
  {
    id: 54,
    name: "Mary Wambui",
    location: "Kiuu Ward",
    orders: 10,
    status: "Active",
    sustainabilityScore: 61,
  },
  {
    id: 55,
    name: "John Njeri",
    location: "Kinale Ward",
    orders: 5,
    status: "Active",
    sustainabilityScore: 50,
  },
  {
    id: 56,
    name: "Thomas Karanja",
    location: "Dagoretti North",
    orders: 7,
    status: "Active",
    sustainabilityScore: 83,
  },
  {
    id: 57,
    name: "John Kimani",
    location: "Masinga",
    orders: 8,
    status: "Active",
    sustainabilityScore: 97,
  },
  {
    id: 58,
    name: "Grace Nyambura",
    location: "Mathare",
    orders: 5,
    status: "Active",
    sustainabilityScore: 98,
  },
  {
    id: 59,
    name: "Esther Njeri",
    location: "Githunguri",
    orders: 7,
    status: "Active",
    sustainabilityScore: 67,
  },
  {
    id: 60,
    name: "George Jepkorir",
    location: "Kamukunji",
    orders: 7,
    status: "Active",
    sustainabilityScore: 99,
  },
  {
    id: 61,
    name: "Anne Wambui",
    location: "Kikuyu",
    orders: 10,
    status: "Active",
    sustainabilityScore: 78,
  },
  {
    id: 62,
    name: "Anne Jepkorir",
    location: "Kiuu Ward",
    orders: 5,
    status: "Active",
    sustainabilityScore: 69,
  },
  {
    id: 63,
    name: "Stephen Maina",
    location: "Township Ward",
    orders: 4,
    status: "Active",
    sustainabilityScore: 83,
  },
  {
    id: 64,
    name: "Stephen Kamau",
    location: "Kahawa Sukari Ward",
    orders: 8,
    status: "Active",
    sustainabilityScore: 61,
  },
  {
    id: 65,
    name: "Margaret Nyambura",
    location: "Gatanga",
    orders: 3,
    status: "Active",
    sustainabilityScore: 60,
  },
  {
    id: 66,
    name: "Samuel Njoroge",
    location: "Embakasi North",
    orders: 7,
    status: "Active",
    sustainabilityScore: 67,
  },
  {
    id: 67,
    name: "Ruth Njoroge",
    location: "Kamburu Ward",
    orders: 5,
    status: "Active",
    sustainabilityScore: 67,
  },
  {
    id: 68,
    name: "Ruth Karanja",
    location: "Kijabe Ward",
    orders: 9,
    status: "Active",
    sustainabilityScore: 65,
  },
  {
    id: 69,
    name: "Margaret Wanjiku",
    location: "Gatundu South",
    orders: 7,
    status: "Active",
    sustainabilityScore: 89,
  },
  {
    id: 70,
    name: "James Kariuki",
    location: "Kasarani",
    orders: 5,
    status: "Active",
    sustainabilityScore: 53,
  },
  {
    id: 71,
    name: "Esther Anyango",
    location: "Kathiani",
    orders: 2,
    status: "Active",
    sustainabilityScore: 76,
  },
  {
    id: 72,
    name: "Elizabeth Kimani",
    location: "Embakasi East",
    orders: 9,
    status: "Active",
    sustainabilityScore: 79,
  },
  {
    id: 73,
    name: "Samuel Kamau",
    location: "Hospital Ward",
    orders: 4,
    status: "Active",
    sustainabilityScore: 79,
  },
  {
    id: 74,
    name: "Sarah Wanjiku",
    location: "Kinale Ward",
    orders: 7,
    status: "Active",
    sustainabilityScore: 89,
  },
  {
    id: 75,
    name: "Peter Maina",
    location: "Kasarani",
    orders: 5,
    status: "Active",
    sustainabilityScore: 50,
  },
  {
    id: 76,
    name: "James Jepkorir",
    location: "Ol Kalou Central Ward",
    orders: 10,
    status: "Active",
    sustainabilityScore: 94,
  },
  {
    id: 77,
    name: "Ruth Anyango",
    location: "Kandara",
    orders: 6,
    status: "Active",
    sustainabilityScore: 87,
  },
  {
    id: 78,
    name: "Paul Anyango",
    location: "Nyanduma Ward",
    orders: 2,
    status: "Active",
    sustainabilityScore: 70,
  },
  {
    id: 79,
    name: "Peter Kariuki",
    location: "Thika Town",
    orders: 7,
    status: "Active",
    sustainabilityScore: 80,
  },
  {
    id: 80,
    name: "Stephen Kariuki",
    location: "Yatta",
    orders: 2,
    status: "Active",
    sustainabilityScore: 91,
  },
  {
    id: 81,
    name: "Anne Muthoni",
    location: "Embakasi Central",
    orders: 1,
    status: "Active",
    sustainabilityScore: 67,
  },
  {
    id: 82,
    name: "Grace Kipchumba",
    location: "Kipipiri",
    orders: 10,
    status: "Active",
    sustainabilityScore: 60,
  },
  {
    id: 83,
    name: "Lucy Wambui",
    location: "Kamenu Ward",
    orders: 3,
    status: "Active",
    sustainabilityScore: 72,
  },
  {
    id: 84,
    name: "David Kipchumba",
    location: "Kahawa Sukari Ward",
    orders: 2,
    status: "Active",
    sustainabilityScore: 80,
  },
  {
    id: 85,
    name: "Florence Wangari",
    location: "Machakos Town",
    orders: 8,
    status: "Active",
    sustainabilityScore: 96,
  },
  {
    id: 86,
    name: "John Chebet",
    location: "Matungulu",
    orders: 7,
    status: "Active",
    sustainabilityScore: 97,
  },
  {
    id: 87,
    name: "Catherine Wambui",
    location: "Gatundu South",
    orders: 2,
    status: "Active",
    sustainabilityScore: 84,
  },
  {
    id: 88,
    name: "Thomas Maina",
    location: "Roysambu",
    orders: 4,
    status: "Active",
    sustainabilityScore: 55,
  },
  {
    id: 89,
    name: "James Anyango",
    location: "Embakasi East",
    orders: 7,
    status: "Active",
    sustainabilityScore: 51,
  },
  {
    id: 90,
    name: "Peter Kibet",
    location: "Makadara",
    orders: 1,
    status: "Active",
    sustainabilityScore: 55,
  },
  {
    id: 91,
    name: "Jane Wambui",
    location: "Kabete",
    orders: 8,
    status: "Active",
    sustainabilityScore: 63,
  },
  {
    id: 92,
    name: "Florence Kariuki",
    location: "Lari",
    orders: 7,
    status: "Active",
    sustainabilityScore: 67,
  },
  {
    id: 93,
    name: "Grace Anyango",
    location: "Matungulu",
    orders: 8,
    status: "Active",
    sustainabilityScore: 55,
  },
  {
    id: 94,
    name: "James Maina",
    location: "Kijabe Ward",
    orders: 10,
    status: "Active",
    sustainabilityScore: 66,
  },
  {
    id: 95,
    name: "Patrick Kimani",
    location: "Kasarani",
    orders: 8,
    status: "Active",
    sustainabilityScore: 100,
  },
  {
    id: 96,
    name: "Elizabeth Karanja",
    location: "Matungulu",
    orders: 5,
    status: "Active",
    sustainabilityScore: 97,
  },
  {
    id: 97,
    name: "Mary Omondi",
    location: "Kinangop",
    orders: 4,
    status: "Active",
    sustainabilityScore: 63,
  },
  {
    id: 98,
    name: "James Kiptoo",
    location: "Kiambaa",
    orders: 5,
    status: "Active",
    sustainabilityScore: 100,
  },
  {
    id: 99,
    name: "Samuel Wambui",
    location: "Biashara Ward",
    orders: 10,
    status: "Active",
    sustainabilityScore: 77,
  },
  {
    id: 100,
    name: "Joseph Nyambura",
    location: "Lang'ata",
    orders: 4,
    status: "Active",
    sustainabilityScore: 86,
  },
];

const activeOrders = [
  { farmerId: 39, order: "5 x 25kg bags", status: "In Transit" },
  { farmerId: 1, order: "6 x 50kg bags", status: "In Transit" },
  { farmerId: 25, order: "1 x 50kg bags", status: "Pending Delivery" },
  { farmerId: 36, order: "6 x 25kg bags", status: "Pending Delivery" },
  { farmerId: 88, order: "1 x 50kg bags", status: "In Transit" },
  { farmerId: 95, order: "2 x 25kg bags", status: "Pending Delivery" },
  { farmerId: 69, order: "3 x 25kg bags", status: "In Transit" },
  { farmerId: 8, order: "5 x 25kg bags", status: "In Transit" },
  { farmerId: 66, order: "5 x 50kg bags", status: "Pending Delivery" },
  { farmerId: 38, order: "5 x 50kg bags", status: "In Transit" },
  { farmerId: 73, order: "1 x 50kg bags", status: "Pending Delivery" },
  { farmerId: 20, order: "1 x 25kg bags", status: "Pending Delivery" },
];

const summaryData = {
  totalFarmers: farmers.length,
  activeFarmers: farmers.filter((f) => f.status.toLowerCase() === "active")
    .length,
  totalOrders: farmers.reduce((acc, f) => acc + f.orders, 0),
};
