// This is a simple array of supplier objects
const suppliers = [
  {
    id: 1,
    name: "Hezekiah Mburu",
    phone: "+254 754711451",
    location: "Ruiru",
    reliability: 4,
    status: "active",
    image: "/src/images/Ecorich_logo.png",
  },
  {
    id: 2,
    name: "Lawrence Njomo",
    phone: "+254 105426353",
    location: "Kahawa Sukari",
    reliability: 5,
    status: "active",
    image: "/src/images/Ecorich_logo.png  ",
  },
  {
    id: 3,
    name: "Joseph Kamau kanyingi",
    phone: "0112642139",
    location: "Thika",
    reliability: 3,
    status: "inactive",
    image: "/src/images/Ecorich_logo.png",
  },
  {
    id: 4,
    name: "Mutwii Evans Musyoki",
    phone: "0717251343",
    location: "Kahawa Wendani",
    reliability: 4,
    status: "active",
    image: "/src/images/Ecorich_logo.png",
  },
  {
    id: 5,
    name: "JUDITH MACHARIA",
    phone: "0717246031",
    location: "Bypass",
    reliability: 5,
    status: "active",
    image: "/src/images/Ecorich_logo.png",
  },
  {
    id: 6,
    name: "John Samuel Gioche",
    phone: "0112962132",
    location: "Ruai",
    reliability: 2,
    status: "inactive",
    image: "/src/images/Ecorich_logo.png",
  },
  {
    id: 7,
    name: "Victoria Theuri",
    phone: "0701266048",
    location: "Ruai",
    reliability: 4,
    status: "active",
    image: "/src/images/Ecorich_logo.png",
  },
  {
    id: 8,
    name: "Glory kendi Cherop",
    phone: "0741992093",
    location: "Ruai",
    reliability: 3,
    status: "active",
    image: "/src/images/Ecorich_logo.png",
  },
  {
    id: 9,
    name: "Joseph Muraya",
    phone: "0796973123",
    location: "Kahawa Sukari",
    reliability: 5,
    status: "active",
    image: "/src/images/Ecorich_logo.png",
  },
  {
    id: 10,
    name: "Joy Ireri",
    phone: "0741992093",
    location: "Thika",
    reliability: 4,
    status: "active",
    image: "/src/images/Ecorich_logo.png",
  },

  {
    id: 6,
    name: "David Soita",
    phone: "0721946363",
    location: "Karuguru",
    reliability: 2,
    status: "active",
    image: "/src/images/Ecorich_logo.png",
  },
  {
    id: 7,
    name: "Trizah mukung",
    phone: "0702142046",
    location: "Ruiru",
    reliability: 4,
    status: "active",
    image: "/src/images/Ecorich_logo.png",
  },
  {
    id: 8,
    name: "Mercy Njeri kagwathi",
    phone: "+254 712 345678",
    location: "Ruiru",
    reliability: 3,
    status: "inactive",
    image: "/src/images/Ecorich_logo.png",
  },
  {
    id: 9,
    name: "Ndemwa Davies Ndambuki",
    phone: "0795932190",
    location: "Kahawa Sukari",
    reliability: 5,
    status: "active",
    image: "/src/images/Ecorich_logo.png",
  },
  {
    id: 10,
    name: "Reagan Ochieng",
    phone: "+254 712 345678",
    location: "Kahawa Sukari",
    reliability: 5,
    status: "active",
    image: "/src/images/Ecorich_logo.png",
  },

  {
    id: 6,
    name: "Sandra Anne Mutinda",
    phone: "0754711451",
    location: "Karuguru",
    reliability: 2,
    status: "inactive",
    image: "/src/images/Ecorich_logo.png",
  },
  {
    id: 8,
    name: "Brian Kasike",
    phone: "0720424751",
    location: "Karuguru",
    reliability: 3,
    status: "active",
    image: "/src/images/Ecorich_logo.png",
  },
  {
    id: 9,
    name: "GARD ALSON SAFARI",
    phone: "0795932190",
    location: "Kahawa Sukari",
    reliability: 5,
    status: "active",
    image: "/src/images/Ecorich_logo.png",
  },
  {
    id: 10,
    name: "DENIS KAMAU",
    phone: "0740119664",
    location: "Kahawa Sukari",
    reliability: 4,
    status: "active",
    image: "/src/images/Ecorich_logo.png",
  },

  {
    id: 6,
    name: "Timothy Mogunde Morandi",
    phone: "0748793640",
    location: "Kahawa Wendani",
    reliability: 2,
    status: "active",
    image: "/src/images/Ecorich_logo.png",
  },
  {
    id: 7,
    name: "BONGOKO DENVER J. OGAMBA",
    phone: "0702142046",
    location: "Ruai",
    reliability: 4,
    status: "active",
    image: "/src/images/Ecorich_logo.png",
  },
  {
    id: 8,
    name: "MAUREEN CHEBET TALLAM",
    phone: "0112962132",
    location: "Ruiru",
    reliability: 3,
    status: "inactive",
    image: "/src/images/Ecorich_logo.png",
  },
];
