// This is a simple array of supplier objects
const supplier = [
  {
    id: 1,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Ruiru",
    reliability: 4,
    status: "active",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 2,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Kahawa Sukari",
    reliability: 5,
    status: "active",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 3,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Thika",
    reliability: 3,
    status: "inactive",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 4,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Kahawa Wendani",
    reliability: 4,
    status: "active",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 5,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Bypass",
    reliability: 5,
    status: "active",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 6,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Karuguru",
    reliability: 2,
    status: "inactive",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 7,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Ruai",
    reliability: 4,
    status: "active",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 8,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Ruiru",
    reliability: 3,
    status: "inactive",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 9,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Kahawa Sukari",
    reliability: 5,
    status: "active",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 10,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Thika",
    reliability: 4,
    status: "active",
    image: "/src/images/ruth_ecorich.jpg",
  },

  {
    id: 6,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Karuguru",
    reliability: 2,
    status: "inactive",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 7,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Ruai",
    reliability: 4,
    status: "active",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 8,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Ruiru",
    reliability: 3,
    status: "inactive",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 9,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Kahawa Sukari",
    reliability: 5,
    status: "active",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 10,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Thika",
    reliability: 4,
    status: "active",
    image: "/src/images/ruth_ecorich.jpg",
  },

  {
    id: 6,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Karuguru",
    reliability: 2,
    status: "inactive",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 7,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Ruai",
    reliability: 4,
    status: "active",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 8,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Ruiru",
    reliability: 3,
    status: "inactive",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 9,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Kahawa Sukari",
    reliability: 5,
    status: "active",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 10,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Thika",
    reliability: 4,
    status: "active",
    image: "/src/images/ruth_ecorich.jpg",
  },

  {
    id: 6,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Karuguru",
    reliability: 2,
    status: "inactive",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 7,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Ruai",
    reliability: 4,
    status: "active",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 8,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Ruiru",
    reliability: 3,
    status: "inactive",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 9,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Kahawa Sukari",
    reliability: 5,
    status: "active",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 10,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Thika",
    reliability: 4,
    status: "active",
    image: "/src/images/ruth_ecorich.jpg",
  },

  {
    id: 6,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Karuguru",
    reliability: 2,
    status: "inactive",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 7,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Ruai",
    reliability: 4,
    status: "active",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 8,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Ruiru",
    reliability: 3,
    status: "inactive",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 9,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Kahawa Sukari",
    reliability: 5,
    status: "active",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 10,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Thika",
    reliability: 4,
    status: "active",
    image: "/src/images/ruth_ecorich.jpg",
  },

  {
    id: 6,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Karuguru",
    reliability: 2,
    status: "inactive",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 7,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Ruai",
    reliability: 4,
    status: "active",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 8,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Ruiru",
    reliability: 3,
    status: "inactive",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 9,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Kahawa Sukari",
    reliability: 5,
    status: "active",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 10,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Thika",
    reliability: 4,
    status: "active",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 6,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Karuguru",
    reliability: 2,
    status: "inactive",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 7,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Ruai",
    reliability: 4,
    status: "active",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 8,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Ruiru",
    reliability: 3,
    status: "inactive",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 9,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Kahawa Sukari",
    reliability: 5,
    status: "active",
    image: "/src/images/ruth_ecorich.jpg",
  },
  {
    id: 10,
    name: "Joseph Kamau",
    phone: "+254 712 345678",
    location: "Thika",
    reliability: 4,
    status: "active",
    image: "/src/images/ruth_ecorich.jpg",
  },
];
