const trainings = [
  {
    id: 1,
    title: "Sustainable Farming Workshop",
    category: "Farmer",
    mode: "In-Person",
    date: "Jan 10, 2026",
    location: "Nyandarua",
    status: "Upcoming",
    participants: 154,
  },
  {
    id: 2,
    title: "Waste Management Training",
    category: "Traders",
    mode: "Online",
    date: "Juna 15, 2025",
    location: "Thika",
    status: "Completed",
    participants: 32,
  },
  {
    id: 3,
    title: "Eco-Fertilizer Application",
    category: "Farmers",
    mode: "In-Person",
    date: "Jan 10, 2025",
    location: "Kilimambogo",
    status: "Completed",
    participants: 53,
  },
  {
    id: 4,
    title: "Team Safety Session",
    category: "Traders",
    mode: "In-Person",
    date: "Nov 2, 2024",
    location: "Kikuyu",
    status: "Completed",
    participants: 81,
  },
  {
    id: 5,
    title: "Output maximization Strategies",
    category: "Farmers",
    mode: "In-Person",
    date: "Aug 12, 2024",
    location: "Kikuyu",
    status: "Completed",
    participants: 116,
  },
  {
    id: 6,
    title: "Advantages of organic farming",
    category: "Farmers",
    mode: "In-Person",
    date: "Mar 5, 2024",
    location: "Kilimambogo",
    status: "Completed",
    participants: 128,
  },
  {
    id: 7,
    title: "Farm health and safety measures",
    category: "Farmers",
    mode: "In-Person",
    date: "Dec 28, 2024",
    location: "Nyandarua",
    status: "Completed",
    participants: 92,
  },
  ,
  {
    id: 8,
    title: "Farmers market trends 2024",
    category: "Farmers",
    mode: "Online",
    date: "Dec 15, 2024",
    location: "Thika",
    status: "Completed",
    participants: 32,
  },
];

const summaryData = {
  total: trainings.length,
  upcoming: trainings.filter((t) => t.status === "Upcoming").length,
  completed: trainings.filter((t) => t.status === "Completed").length,
  participants: trainings.reduce((acc, t) => acc + t.participants, 0),
};
